project-a-26-main/NewLousList/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'NewLousList'
urlpatterns = [
    path('', views.index, name="index"),
    path('subject/<str:subject_name>/', views.courses_by_subject, name='courses_by_subject'),
    path('subject/<str:subject_name>/<int:course_id>/', views.single_course, name='single_course'),
    path('logout', LogoutView.as_view(), name="logout"),
    path("search/<str:subject_name>/", views.search_courses, name="search"),
    path('friendsearch/', views.friend_search, name="friend_search"),
    path('friends/', views.view_friends, name="friends"),
    path('profile/', views.view_profile, name="profile"),
    path('editprofile/', views.edit_profile, name="edit_profile"),
    path('profile/<str:owner>', views.view_profile, name="profile"),
    path('friendrequests/', views.view_requests, name="requests"),
    path("search/", views.search_courses, name="search"),
    path('cart/', views.cart_view, name='view_cart'),
    path('cart/<int:course_id>/', views.cart_add, name='cart'),
    path('cart/remove/<int:course_id>/', views.cart_delete, name='remove_cart'),
    path('schedule/', views.create_schedule, name='schedule'),
    path('schedule/<str:owner>/', views.create_schedule, name='schedule'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    #path('comments/<str:owner>/', views.create_schedule, name='comments'),
    #path('comments/', views.create_schedule, name='schedule'),
    path('review', views.review, name="review"),
    path('review_confirm', views.review_confirm, name="review_confirm"),
]

project-a-26-main/mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('NewLousList/', include('NewLousList.urls')),
    path('', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
]

project-a-26-main/NewLousList/forms.py
from django.forms import ModelForm
from django import forms
from .models import Review

class NewReview(ModelForm):
    class Meta:
        model = Review
        fields = '__all__'

class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    grad_year = forms.IntegerField()
    major = forms.CharField(max_length=50)

project-a-26-main/NewLousList/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404,render
import requests
from .models import Subject, Course, FriendList, FriendRequest, ShoppingCart, UserInfo, Comments, Review
from django.db.models import Q
from django.contrib.auth.models import User
from .names import get_names
from datetime import time, datetime
from django.contrib.auth.decorators import login_required
from .forms import NewReview, ContactForm
from django.views import generic
from .names import get_names, college_arts_sci, edu_hum_dev_school, engr_school, other_schools

SHOPPING_CART = set()


# Create your views here.
@login_required
def courses_by_subject(request, subject_name):

    #retrieve the subject based on its id
    #subject = get_object_or_404(Subject, pk=subject_id)


    subject = get_object_or_404(Subject, subject=subject_name)
    #subject = Subject.objects.get(subject=subject_name)

    #pull data from api for the specific subject
    response = requests.get('http://luthers-list.herokuapp.com/api/dept/' + subject.subject + '?format=json')

    #convert reponse data into json
    courses = response.json()

    course_titles = {}
    course_gpa = {}

    course_id = {}

    i = 1
    # for each subject, create a python object using model
    for course in courses:

        # add course titles to a dictionary to help organize classes that have the same title
        if course['description'] not in course_titles:
            course_titles[course['description']] = []
            course_gpa[course['description']] = 0

         # create course objects for each subject

        meetings = course['meetings']

        # Standardize course meeting times
        # First check if the list isn't empty
        if len(meetings) > 0:
            for meeting in meetings:
                # Then check if start and end times have actual values to them
                if (meeting['start_time'] != '') and meeting['end_time'] != '':
                    # Convert hours to GMT-5 standard time format
                    start_hour = meeting['start_time'][0:2]
                    start_hour = int(start_hour)
                    start_minute = meeting['start_time'][3:5]
                    start_minute = int(start_minute)
                    end_hour = meeting['end_time'][0:2]
                    end_hour = int(end_hour)
                    end_minute = meeting['end_time'][3:5]
                    end_minute = int(end_minute)

                    start_time = time(start_hour, start_minute)
                    meeting['start_time'] = start_time.strftime('%I:%M %p')
                    end_time = time(end_hour, end_minute)
                    meeting['end_time'] = end_time.strftime('%I:%M %p')
            course['meetings'] = meetings

        Course.objects.get_or_create(
            instructor_name=course['instructor']['name'],
            instructor_email=course['instructor']['email'],
            course_number=course['course_number'],
            semester_code=course['semester_code'],
            course_section=course['course_section'],
            subject=course['subject'],
            catalog_number=course['catalog_number'],
            description=course['description'],
            units=course['units'],
            component=course['component'],
            class_capacity=course['class_capacity'],
            wait_list=course['wait_list'],
            wait_cap=course['wait_cap'],
            enrollment_total=course['enrollment_total'],
            enrollment_available=course['enrollment_available'],
            topic=course['topic'],
            meetings=course['meetings']
        )

    # organize courses by their class name in a dictonary; key: course name, value: list of courses that share the course name
    for course in courses:
        c = Course.objects.get(course_number=course['course_number'])
        c_id = c.id
        course_with_id = {c_id:course}
        course_titles[course['description']].append(course_with_id)

    #display courses for that subject
    return render(request, 'NewLousList/courses_by_subject.html', {'subject': subject,  'course_titles': course_titles, 'subject_id': subject_name})

def single_course(request, subject_name, course_id):
    #subject = get_object_or_404(Subject, pk=subject_id)
    subject = get_object_or_404(Subject, subject=subject_name)
    response = requests.get('http://luthers-list.herokuapp.com/api/dept/' + subject.subject + '?format=json')
    courses = response.json()
    single_course = 0
    for course in courses:
        if course['course_number'] == course_id:
            single_course = course

    meetings = single_course['meetings']

    # Standardize course meeting times
    # First check if the list isn't empty
    if len(meetings) > 0:
        for meeting in meetings:
            # Then check if start and end times have actual values to them
            if (meeting['start_time'] != '') and meeting['end_time'] != '':
                # Convert hours to GMT-5 standard time format
                start_hour = meeting['start_time'][0:2]
                start_hour = int(start_hour)
                start_minute = meeting['start_time'][3:5]
                start_minute = int(start_minute)
                end_hour = meeting['end_time'][0:2]
                end_hour = int(end_hour)
                end_minute = meeting['end_time'][3:5]
                end_minute = int(end_minute)

                start_time = time(start_hour, start_minute)
                meeting['start_time'] = start_time.strftime('%I:%M %p')
                end_time = time(end_hour, end_minute)
                meeting['end_time'] = end_time.strftime('%I:%M %p')
        single_course['meetings'] = meetings

    html = 'https://vagrades.com/api/uva/course/'
    new_html = html + subject_name + str(single_course['catalog_number'])
    response = requests.get(new_html)
    gpa = 0
    letter = "GPA NOT FOUND"
    if response:
        class_info = response.json()
        gpa = class_info["course"]["avg"]
        if gpa:
            gpa  = round(gpa,2)
             
            if gpa > 3.7:
                letter = "A"
            elif gpa > 3.3:
                letter = "A-"
            elif gpa > 3.0:
                letter = "B+"
            elif gpa > 2.7:
                letter = "B"
            elif gpa > 2.3:
                letter = "B-"
            elif gpa > 2.0:
                letter = "C+"
            elif gpa > 1.7:
                letter = "C"
            elif gpa > 1.3:
                letter = "C-"
            elif gpa > 1.0:
                letter = "D+"
            elif gpa > 0.7:
                letter = "D"
            elif gpa > 0.3:
                letter = "D-"
            else:
                letter = "F"
    gpa = str(gpa) + " (" + letter + ")" 
    class_reviews = []
    for r in Review.objects.all():
        print(r.review_text)
        if r.subject == subject_name and r.course_number == single_course['catalog_number']:
            class_reviews.append(r)
    return render(request, 'NewLousList/single_course.html', {'course_id' : course_id, 'subject_id' : subject_name, 'single_course' : single_course, 'gpa': gpa, 'all_reviews' : class_reviews})

@login_required
def index(request):
    
    # pull data on subjects from api
    response = requests.get('http://luthers-list.herokuapp.com/api/deptlist?format=json')

    # convert reponse data into json
    subjects = response.json()

    #dictionary for actual subject names, so we dont have to use mnemonics

    engr_list = []
    college_list = []
    edu_list = []
    other_list = []

    #for each subject, create a python object using model
    for sub in subjects:
        Subject.objects.get_or_create(subject=sub['subject'],name=get_names[sub['subject']])


    #list of all the subjects
    allSubjects = Subject.objects.all()

    # Sort Subjects into schools
    for sub in college_arts_sci.keys():
        # print(sub)
        # temp_subs = Subject.objects.filter(Q(subject__icontains=sub))
        try:
            college_list.append(get_object_or_404(Subject, subject=sub))
        except:
            college_list.append(Subject.objects.filter(Q(subject__icontains=sub))[1])  
        # college_list.append(Subject.objects.filter(Q(subject__icontains=sub))[0])

    for sub in engr_school.keys():
        try:
            engr_list.append(get_object_or_404(Subject, subject=sub))
        except:
            engr_list.append(Subject.objects.filter(Q(subject__icontains=sub))[1]) 

    for sub in edu_hum_dev_school.keys():
        try:
            edu_list.append(get_object_or_404(Subject, subject=sub))
        except:
            edu_list.append(Subject.objects.filter(Q(subject__icontains=sub))[1]) 

    for sub in other_schools.keys():
        try:
            other_list.append(get_object_or_404(Subject, subject=sub))
        except:
            other_list.append(Subject.objects.filter(Q(subject__icontains=sub))[1]) 

    filteredSubjects = []

    context = {
        'subjects': allSubjects,
        'filtered': filteredSubjects,
        'engr_list': engr_list,
        'college_list': college_list,
        'edu_list': edu_list,
        'other_list': other_list
    }

    # Search feature for departments
    if 'search' in request.GET:
        q = request.GET['search']
        filteredSubjects = Subject.objects.filter(Q(name__icontains=q) | Q(subject__icontains=q))

        context = {
            'filtered': filteredSubjects
        }

        return render(request, "NewLousList/index.html", context)

    return render(request, "NewLousList/index.html", context)


@login_required
def search_courses(request, subject_name):

    subject = get_object_or_404(Subject, subject=subject_name)


    if request.method == 'GET':
        title = request.GET.get('title')
        prof = request.GET.get('instructor')
        catalog_num = request.GET.get('catalog_number')
        units = request.GET.get('units')

project-a-26-main/NewLousList/templates/NewLousList/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
         <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <style>
            body {
                margin: 0;
                font-family: Arial, Helvetica, sans-serif;
                min-height: 100vh;
                display: flex;
                flex-direction: column;
            }
            .topnav {
                overflow: hidden;
                background-color: #333;
                text-align: center;
                color: #f2f2f2;
                padding: 14px 16px;
                text-decoration: none;
            }

            .content {
                background-color: #ddd;
                padding: 10px;
                height: 600px;
            }

            .footer {
                background-color: #f1f1f1;
                padding: 10px;
                margin-top: auto;
            }

            {% block css %}
            {% endblock %}
        </style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
        {% block refresh%}
        {% endblock %}
      <li class="nav-item active">
        <a class="nav-link" href = "{% url 'NewLousList:index'  %}">Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Profile</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href = "{% url 'NewLousList:profile' %}">Profile</a>
          <a class="dropdown-item" href = "{% url 'NewLousList:friends' %}">Friends</a>
          <a class="dropdown-item" href = "{% url 'NewLousList:friend_search' %}">Friend Search</a>
          <a class="dropdown-item" href = "{% url 'NewLousList:requests' %}">Friend Requests</a>
        </div>
      </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Schedule</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
            <a class="dropdown-item" href = "{% url 'NewLousList:schedule' %}">Schedule</a>
          <a class="dropdown-item" href = "{% url 'NewLousList:view_cart' %}">Shopping Cart</a>
        </div>
        
      </li>
        <li class="nav-item">
          <a class="nav-link"  href = "{% url 'NewLousList:review' %}">Review a Course</a>
      </li>
        <li class="nav-item">

            <a class="nav-link"  href = "{% url 'NewLousList:logout' %}">Logout</a>
      </li>
    </ul>
  </div>
    {% block search %}
    {% endblock %}
</nav>


<!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark">-->
<!--  <div class="container-fluid">-->
<!--    -->
<!--    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">-->
<!--      <span class="navbar-toggler-icon"></span>-->
<!--    </button>-->
<!--    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">-->
<!--      <div class="navbar-nav">-->
<!--          <a class="nav-link active" aria-current="page" href = "{% url 'NewLousList:index'  %}">Home</a>-->
<!--          <a class="nav-link active" aria-current="page" href = "{% url 'NewLousList:profile' %}">Profile</a>-->
<!--          <a class="nav-link active" aria-current="page" href = "{% url 'NewLousList:friend_search' %}">Friend Search</a>-->

<!--          <a class="nav-link active" aria-current="page" href = "{% url 'NewLousList:view_cart' %}">Shopping Cart</a>-->
<!--          <a class="nav-link active" aria-current="page" href = "{% url 'NewLousList:schedule' %}">Schedule</a>-->
<!--          <a class="nav-link active" aria-current="page" href = "{% url 'NewLousList:logout' %}">Logout</a>-->

<!--&lt;!&ndash;        <a class="nav-link" href="{% url 'NewLousList:logout' %}">Logout</a>&ndash;&gt;-->
<!--&lt;!&ndash;        <a class="nav-link" href="#">Pricing</a>&ndash;&gt;-->
<!--&lt;!&ndash;        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>&ndash;&gt;-->
<!--      </div>-->
<!--    </div>-->
<!--    -->
<!--  </div>-->


<!--&lt;!&ndash;     Nav bar source code: https://getbootstrap.com/docs/5.0/components/navbar/&ndash;&gt;-->
<!--</nav>-->

    {% block specifics %}
    {% endblock %}
    <body>
        {% block content %}
        {% endblock %}

        <footer class="text- mt-auto">
        <div class="p-1 bg-dark text-white text-end">
            <p>Courtesy of CS 3240 group A-26.</p>
        </div>
    </footer>
    </body>
</html>

project-a-26-main/NewLousList/templates/NewLousList/courses_by_subject.html
{% extends 'NewLousList/base.html' %}
        {% block css %}
            .button {
                text-decoration: none;
            }

            /* Style for button attribute */
            .button a {
                float: left;
                display: block;
                text-align: center;
                padding: 10px 12px;
                color: #030303;
                background-color: rgba(177, 177, 177, 0.768);
                transition: 500ms;
                border-radius: 10px;
            }

            .button a:link {
                text-decoration: none;
            }

            /* Style button after clicked */
            .button a:visited {
                text-decoration: none;
                color:#060606;
            }

            /* Change color and radius on hover with added transition */
            .button a:hover {
                float: left;
                text-decoration: none;
                background-color: rgba(192, 192, 192, 0.768);
                transition: 400ms;
                transition-delay: 100ms;
                border-radius: 20px;
            }

            .button a:active {
                text-decoration: none;
                background-color: rgba(218, 131, 0, 0.768);
            }

            .wrap-collabsible {
              margin-bottom: 1.2rem 0;
            }

            input[type='checkbox'] {
              display: none;
            }

            .lbl-toggle {
              display: block;

              font-weight: bold;
              font-family: monospace;
              font-size: 1.2rem;
              text-transform: uppercase;
              text-align: center;

              padding: 1rem;

              color: #FFFFFF;
              background: rgba(5, 9, 9, 0.64);

              cursor: pointer;

              border-radius: 7px;
              transition: all 0.25s ease-out;
            }

            .lbl-toggle:hover {
              color: #FFFFFF;
            }

            .lbl-toggle::before {
              content: ' ';
              display: inline-block;

              border-top: 5px solid transparent;
              border-bottom: 5px solid transparent;
              border-left: 5px solid currentColor;
              vertical-align: middle;
              margin-right: .7rem;
              transform: translateY(-2px);

              transition: transform .2s ease-out;
            }

            .toggle:checked + .lbl-toggle::before {
              transform: rotate(90deg) translateX(-3px);
            }

            .collapsible-content {
              max-height: 0px;
              overflow: hidden;
              transition: max-height .25s ease-in-out;
            }

            .toggle:checked + .lbl-toggle + .collapsible-content {
              max-height: 100vh;
            }

            .toggle:checked + .lbl-toggle {
              border-bottom-right-radius: 0;
              border-bottom-left-radius: 0;
            }

            .collapsible-content .content-inner {
              background: rgba(142, 167, 167, 0.27);
              border-bottom: 1px solid rgba(142, 167, 167, 0.27);
              border-bottom-left-radius: 7px;
              border-bottom-right-radius: 7px;
              padding: .5rem 1rem;
            }

        {% endblock %}


  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

  {% block refresh %}
    <a class="navbar-brand" href="{% url 'NewLousList:courses_by_subject' subject.subject %}">

        {% if subject.name != '' %}
            {{subject}} Courses
        {% else %}
            {{subject.subject}} Courses
        {% endif %}
    </a>
  {% endblock %}

        {% block search%}
        {% endblock %}


    {% block specifics %}



<div class="wrap-collabsible">
  <input id="collapsible" class="toggle" type="checkbox">
  <label for="collapsible" class="lbl-toggle">Search Courses</label>
  <div class="collapsible-content">
    <div class="content-inner">
  <form style="padding-top: 20px; padding-left: 10px; padding-bottom: 20px" action="{% url 'NewLousList:search' subject.subject %}" method="GET" >

    Title <input type="text" name="title" value="{{request.GET.title}}" placeholder=" 'Software Testing' "/>
    Instructor <input type="text" name="instructor" value="{{request.GET.instructor}}" placeholder="Ex: 'Paul McBurney'"/>
    Catalog Number <input type="text" name="catalog_number" value="{{request.GET.catalog_number}}" placeholder="Ex: '1010'"/>
    Units <input type="text" name="units" value="{{request.GET.units}}" placeholder="Ex: '3'"/>
    Component <input type="text" name="component" value="{{request.GET.component}}" placeholder="'Ex: 'LEC'"/>
    <input type="submit" name="submit" value="Search"/>

</form>
</div>
  </div>
</div>

    {% endblock %}




  {% block content %}
                {% for key,value in course_titles.items %}
                    <tr>
                            <div class="container mt-5">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>{{ key }}</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        {% for class in value %}
                                        {% for id_key, class_value in class.items %}


                                        <tr>
                                            <td>
                                                <div style="float:left;width:12%;">
                                                    <a aria-current="page" href = "{% url 'NewLousList:single_course' subject_id class_value.course_number%}">{{ class_value.subject }} {{ class_value.catalog_number}}: {{ class_value.course_number }}</a>
                                                </div>

                                                <div style="float:left;width:4%;">
                                                    {{ class_value.course_section}}
                                                </div>

                                                <div style="float:left;width:9%;">
                                                    {{class_value.component}} ({{class_value.units}} units)
                                                </div>

                                                <div style="float:left;width:14%;">
                                                    Open seats: {{ class_value.enrollment_available}}/{{class_value.class_capacity}}
                                                </div>

                                                <div style="float:left;width:11%;">
                                                    {{ class_value.instructor.name}}
                                                </div>
                                              <font size="2.5">
                                                <div style="float:left;width:28%;">
                                                    {% for time in class_value.meetings %}
                                                    {% for key,val in time.items %}
                                                    {% if key == 'start_time' %}
                                                    <div style="float:left;width:25%;">
                                                        {{ val }} -
                                                    </div>
                                                    {% else %}
                                                    <div style="float:left;width:25%;">
                                                        {{ val }}
                                                    </div>
                                                    {% endif %}
                                                    {% endfor %}
                                                    {% endfor %}
                                                </div>
                                            </font>

                                                <div style="float:right;width:15%;">
                                                    <div class="button">
                                                        <form method="GET" action="{% url 'NewLousList:cart' id_key %}">
                                                            <!-- <button type="submit">Add to Shopping Cart</button> -->
                                                            <input type="submit" name="add_cart_button" value="Add to Shopping Cart"></input>
                                                        </form>
                                                    </div>
                                                    <!-- <button type="submit">Add to Shopping Cart</button> -->
                                                </div>

                                            </td>
                                        </tr>
                                        {% endfor %}
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                    </tr>
                    {% endfor %}
    <script>
        var myVar;

        function myFunction() {
            myVar;
        }

    </script>

   {% endblock %}

project-a-26-main/NewLousList/templates/NewLousList/edit_profile.html
{% extends 'NewLousList/base.html' %}
        {% block css %}
            .button {
                text-decoration: none;
            }

            /* Style for button attribute */
            .button a {
                float: left;
                display: block;
                text-align: center;
                padding: 10px 12px;
                color: #030303;
                background-color: rgba(177, 177, 177, 0.768);
                transition: 500ms;
                border-radius: 10px;
            }

            .button a:link {
                text-decoration: none;
            }

            /* Style button after clicked */
            .button a:visited {
                text-decoration: none;
                color:#060606;
            }

            /* Change color and radius on hover with added transition */
            .button a:hover {
                float: left;
                text-decoration: none;
                background-color: rgba(192, 192, 192, 0.768);
                transition: 400ms;
                transition-delay: 100ms;
                border-radius: 20px;
            }

            .button a:active {
                text-decoration: none;
                background-color: rgba(218, 131, 0, 0.768);
            }
        {% endblock %}

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    {% block refresh%}
     <a class="navbar-brand" href = "{% url 'NewLousList:profile' %}">{{user}}</a>
    {% endblock %}

      {% block search%}
      {% endblock %}

      {% block specifics %}
      {% endblock %}

{% block content %}
<div class = "container mt-4">
    <h3>
        {{profile.user.username}}
    </h3>
            <form action="{% url 'NewLousList:edit_profile' %}" method="post">{% csrf_token %}
                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control" id="first_name" name = "first_name" placeholder="John" value = "{{profile.first_name}}">
                </div>
                <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input type="text" class="form-control" id="last_name" name = "last_name" value = "{{profile.last_name}}" placeholder="Doe">
                </div>
                <div class="form-group">
                    <label for="major">Major</label>
                    <input type="text" class="form-control" id="major" name = "major" value = "{{profile.major}}" placeholder="Computer Science">
                </div>
                <div class="form-group">
                    <label for="grad_year">Graduation Year</label>
                    <input min="{{year}}" required type="number" class="form-control" id="grad_year" value = "{{profile.grad_year}}" name = "grad_year" placeholder="2000">
                </div>
                <div class="form-group">
                    <input class = "btn btn-primary mt-2" type="submit" value="Update Profile">
                </div>
              </form>
    </div>
    

    {% endblock %}

project-a-26-main/NewLousList/templates/NewLousList/review.html
{% extends 'NewLousList/base.html' %}
            {% block css%}
            .buttonClass
            {
                color: black;
                background-color: #86E4EB;

                display:block;
                width: 98%;
                margin-bottom:10px;
                border: 2px solid #86E4EB;
            }
            a:link
            {
                color: #4687DB;
            }
            a:visited
            {
                color: #015249;
            }

        {%endblock%}


        {%block refresh%}
    <a class="navbar-brand" href="{% url 'NewLousList:review' %}">Leave a Review</a>
    {%endblock%}

{%block content%}
<h2>Leave a Review</h2>
<h4>

    <form action="{% url 'NewLousList:review_confirm' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type='submit' >
</form>
</h4>


    {% endblock %}